name: riverpod_lint_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  riverpod_annotation: ^1.2.1  
  hooks_riverpod: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  riverpod_generator: ^1.2.0
  riverpod_lint: ^1.0.0
  build_runner: ^2.3.3
  custom_lint: ^0.2.5

flutter:
  uses-material-design: true
